services:
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "${SERVER_PORT_HOST:-3600}:${SERVER_PORT_CONTAINER:-3300}"
    env_file:
      - ${SERVER_ENV_FILE:-./server/.env}
    volumes:
      - ./server:/app
      - ./server/uploads:/app/uploads
    command: yarn run dev

  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "${CLIENT_PORT_HOST:-3500}:${CLIENT_PORT_CONTAINER:-5173}"
    env_file:
      - ${CLIENT_ENV_FILE:-./client/.env}
    depends_on:
      - server
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    command: yarn run dev

volumes:
  client_node_modules: 